### PR TITLE
fix: resolve issues with vignette

### PR DESCRIPTION
**Pull request by pollend**
I moved the vignette pass into the post_frag.

### CODE REVIEW

**Comment by jdrueckert** [comment]
Gave this a quick test in-game, but it doesn't look right.
Without vignette:
image

With vignette:
image

**Comment by jdrueckert** [comment]
For reference: this is what I would expect the vignette to look like:
(note the darkened corners)
image

**Comment by skaldarnar** [comment]
This might actually fix https://github.com/MovingBlocks/Terasology/issues/4542 - I resized the game window a bit trying to force this issue to pop up, but could not reproduce it.

I'd go for the bold move and claim this fixed - we can always re-open the bug ticket when it occurs again.

Fixes MovingBlocks/Terasology#4542

**Review by skaldarnar — APPROVED** [review]
I'm not happy to see that this removes the vignette shader and rendering node altogether and cramps it into the post processing step. I think one goal of the whole DAG thingy is to be able to implement simple effects like the vignette in any module code and just hook it up with the pipeline.

I'd highly appreciate if we'd try to get into that direction again in the future.

**Comment by pollend** [comment]
@skaldarnar you probably don't want to do that with post processing effects. feeding the output of one shader into the next and redrawing the entire screen. umm ideally you could batch batch and combine effects together in a single shader.

**Pull request merged**
