### PR TITLE
refactor(vignette): use shader to create vignette instead of texture

### PR DESCRIPTION
**Pull request by Imitater967**

### CODE REVIEW

**Comment by BenjaminAmos** [comment]
There are a few warnings from checkstyle in these changes (see https://github.com/Terasology/CoreRendering/pull/80/files#diff-6cc8578782c91ac42bf943d80e8d12166716581e75407504c4120aad864f6119). It would be best if those were fixed, as we aim to have zero warnings in new code.

**Comment by Imitater967** [comment]
Where can i download this plugin?

**Comment by BenjaminAmos** [comment]
> Where can i download this plugin?

Checkstyle should be run as a part of the gradle checks but if you want to see the warnings in IntelliJ then I think we tend to use https://plugins.jetbrains.com/plugin/1065-checkstyle-idea.

**Review by BenjaminAmos — DISMISSED** [review]
For comparison, this is how the vignette looked before:

This is how it looks with this change:


Since one of the first things I usually do with a new game is disable fancy effects (vignette, motion blur, head bobbing, chromatic abberation, etc.), I am unable to comment on if this looks better or not. It it cetainly a more flexible implementation which should be easily tweakable afterwards.

**Comment by Imitater967** [comment]
well, you can modify it at render config now.

**Comment by Imitater967** [comment]
image
how about now? slightly stronger vignette

**Review by jdrueckert — APPROVED** [review]
Tests out fine and the vignette "strength" is great now IMO
@BenjaminAmos already commented on Discord that the code improves things, so I'll go ahead and merge.

**Pull request merged**
