### PR TITLE
chore(rendering): migrate reworking glsl osx

### PR DESCRIPTION
**Pull request by pollend**
PR: https://github.com/MovingBlocks/Terasology/pull/4767

### CODE REVIEW

**Comment by jdrueckert** [comment]
@pollend the engine PR associated with this was merged, but this PR was not. is this still needed?

**Comment by pollend** [comment]
Let's you play on Mac @jdrueckert so this is semi important.

**Comment by jdrueckert** [comment]
> Let's you play on Mac @jdrueckert so this is semi important.

Not sure if sarcasm :thinking: :grin: 
@skaldarnar can you test this?

**Comment by skaldarnar** [comment]
I can't start a game with this on Mac (but I'm not sure this is related to this PR or rendering in general).

```
20:50:52.439 [main] ERROR o.t.g.m.s.JavaModuleClassLoader - Denied access to class (not allowed with this module's permissions): java.io.Serializable
20:50:52.442 [main] ERROR o.t.engine.core.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NoClassDefFoundError: java.io.Serializable
        at org.terasology.core.world.generator.rasterizers.FloraType.<clinit>(FloraType.java:22)
        at org.terasology.core.world.generator.facetProviders.DefaultFloraProvider.<init>(DefaultFloraProvider.java:58)
        at org.terasology.core.world.generator.worldGenerators.SimplexFacetedWorldGenerator.createWorld(SimplexFacetedWorldGenerator.java:68)
        at org.terasology.engine.world.generation.BaseFacetedWorldGenerator.getWorldBuilder(BaseFacetedWorldGenerator.java:94)
        at org.terasology.engine.world.generation.BaseFacetedWorldGenerator.setWorldSeed(BaseFacetedWorldGenerator.java:45)
        at org.terasology.engine.core.modes.loadProcesses.InitialiseWorld.step(InitialiseWorld.java:99)
        at org.terasology.engine.core.modes.StateLoading.update(StateLoading.java:240)
        at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:504)
        at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:464)
        at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:440)
        at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:406)
        at org.terasology.engine.Terasology.main(Terasology.java:179)
```

**Comment by keturn** [comment]
"denied access" to "java.io.Serializable" is, if I recall correctly, the error you got when running with the J9 JVM instead of Hotspot.

**Comment by pollend** [comment]
I think that is unrelated to this.

**Review by Cervator — APPROVED** [review]
I can confirm via my Mac that this _does_ let the player enter a world and see things - although I end up running at below 1 FPS. That may have been a consequence of prior PRs than this one though, without running with this I'd get an entirely black screen + toolbar so this still beats that 👍 

Also seems fine on my Win10, no performance issues there.

**Comment by skaldarnar** [comment]
It indeed was the problem of OpenJ9 vs Hotspot 🙈 can we get a way to figure that out and print a meaningful error message instead?

On the bright side: fps seem fine for me.
image

**Pull request merged**
