### PR TITLE
Upgrading LWJGL to version 3

### PR DESCRIPTION
**Pull request by DarkWeird**

### CODE REVIEW

**Comment by keturn** [comment]
This looks innocent enough. Is it only going to work if engine also has the v3 as well?

**Comment by DarkWeird** [comment]
> This looks innocent enough. Is it only going to work if engine also has the v3 as well?

Yep.

**Comment by pollend** [comment]
This doesn't seem to compile correctly for me. `KeyboardAction` is not defined for me when I attempt to pull this branch.

**Review by skaldarnar — APPROVED** [review]
Approving now so that we can just merge it straight away if engine is ready :+1:

**Pull request merged**
